version: "3.7"
services:
  redis:
    image: redis:latest
    expose:
      - 6379
  web:
    build: .
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis
      - REDIS_PORT=6379
    volumes:
      - .:/usr/lfp-appeals/
      - /usr/lfp-appeals/node_modules
    ports:
      - "3000:3000"
    links:
      - redis
