export const ROOT = '';

export const OTHER_REASON_CATEGORY_PREFIX = `${ROOT}/other`;

export const OTHER_REASON_DISCLAIMER_PAGE_PREFIX = '/other-reason-entry';
export const OTHER_REASON_DISCLAIMER_PAGE_URI = `${OTHER_REASON_CATEGORY_PREFIX}${OTHER_REASON_DISCLAIMER_PAGE_PREFIX}`;

export const OTHER_REASON_PAGE_PREFIX = '/reason-other';
export const OTHER_REASON_PAGE_URI = `${OTHER_REASON_CATEGORY_PREFIX}${OTHER_REASON_PAGE_PREFIX}`;
